### ISSUE TITLE
Spotify Integration 

### ISSUE THREAD

**Issue by bigboy-baby** [7PH/poweraudio#15]
A Suggestion: Make a way to integrate Spotify as the audio source.

**Comment by 7PH** [comment]
I never checked it before, but it is a good idea. The `source` would be data coming from the `segments` array returned by this endpoint: https://developer.spotify.com/documentation/web-api/reference/#/operations/get-audio-analysis 
Will be looking into it 🤔

**Comment by bigboy-baby** [comment]
> 

Yeah I tried for a while last week, prolly a few hours tbh. I couldn't think of a way... but maybe you can

**Comment by 7PH** [comment]
FYI it turns out not to be so easy, so I'll keep this issue open as nice feature to have in the future, but requires more work than I can allocate to this lib atm

**Comment by bigboy-baby** [comment]
yeah I had the same issue, thinking it would be relatively easy, then it not being so.
